### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by josesydor** [greatwhiz/tft_tf2#1]
I've been trying to upgrade TFT to TF2.x based on these guys' work: https://github.com/AmpX-AI/tft-speedup but I couldn't wrap my head around their TFT implementation, much easier to fork yours! :)

Cheers
Z

**Comment by josesydor** [comment]
Although I'm still getting these annoying deprecation warnings such as:

_WARNING:tensorflow:From /content/forecaster/libs/tft_model.py:948: The name tf.keras.layers.CuDNNLSTM is deprecated. Please use tf.compat.v1.keras.layers.CuDNNLSTM instead._

_/usr/local/lib/python3.7/dist-packages/keras/engine/training.py:2470: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version._

**Comment by greatwhiz** [comment]
I can not reproduce your warning, however my environment is colab with tf 2.6. But if it will run and the outputs are fine, you can safely ignore the warnings from tf, because tf always has plenty of warnings. Meanwhile to following the warning guidance is another wise option.
