### ISSUE TITLE
python deep learning

### ISSUE THREAD

**Issue by saranpks** [greatwhiz/tft_tf2#2]
value error :array=[-1.43120418  1.58885804  0.28558148 ... -1.50945972 -0.16713021
 -0.57365613].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by jpbruneton** [comment]
fixed with : 
output[col] = self._target_scaler.inverse_transform(predictions[[col]]) with double [[ ]] instead of one 
see e.g. https://stackoverflow.com/questions/58498187/sklearn-transform-error-expected-2d-array-got-1d-array-instead
