### ISSUE TITLE
best epoch not loaded after fit

### ISSUE THREAD

**Issue by yitelee** [greatwhiz/tft_tf2#6]
class TemporalFusionTransformer(object):
```
        # Load best checkpoint again
        tmp_checkpont = self.get_keras_saved_path(self._temp_folder)
        if os.path.exists(tmp_checkpont):
```
The path can't be seen by os.path.exist, it's always false and the model retains the result from the _last_ but not the _best_ epoch.
Correct it as follows:
```
        if os.path.exists(os.path.join(self._temp_folder, '{}.check.index'.format(self.name))):
```

**Comment by greatwhiz** [comment]
It can be modified. However, I don't think tmp_checkpoint doesn't work for my practical project. Please debug if necessary, it might be different for your environment.
