### ISSUE TITLE
categorical scaler doesn't always apply to the right rows

### ISSUE THREAD

**Issue by yitelee** [greatwhiz/tft_tf2#7]
In data_formatters/electricity.py,
Concat after groupy actually sorted the output slices alphabatically, might not match the order of the original df, should not merged them into new output. Fixed as below:

    # Transform real inputs per entity
    df_list = []
    for identifier, sliced in df.groupby(id_col):

      # Filter out any trajectories that are too short
      if len(sliced) >= self._time_steps:
        sliced_copy = sliced.copy()
        sliced_copy[real_inputs] = self._real_scalers[identifier].transform(
            sliced_copy[real_inputs].values)
        df_list.append(sliced_copy)

    output = pd.concat(df_list, axis=0)

    # Format categorical inputs
    for col in categorical_inputs:
      #string_df = df[col].apply(str)
      string_df = output[col].apply(str) #<===fixed
      output[col] = self._cat_scalers[col].transform(string_df)

    return output

**Comment by greatwhiz** [comment]
The example is only about demonstrating the usage of TFT. It might not be practical. You can safely change it to your actual usage.
