### ISSUE TITLE
TensorFlow 1 or 2?

### ISSUE THREAD

**Issue by giadasp** [greatwhiz/tft_tf2#8]
https://github.com/greatwhiz/tft_tf2/blob/ef179c013999ac6f3923f48e9d7c54372fb607c5/run.sh#L37

Are you using TensorFlow 1 or 2?

**Comment by greatwhiz** [comment]
It is not required to run "run.sh"

**Comment by shai-shechter** [comment]
Which version of tf2 should we install then?
